[package]
name = "tunnel_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-macros = "2.5.0"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
url = "2.5.4"
futures-util = "0.3.31"