[package]
name = "tunnel_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
serde_derive = "1.0.217"
actix-web = "4.9.0"
futures = "0.3.31"
actix = "0.13.5"
bytes = "1.9.0"
reqwest = "0.12.12"